[build]
  base = "ecoshop-frontend/sustainamart"  # Make sure this path is correct
  publish = "ecoshop-frontend/sustainamart/dist"  # Path to the dist directory
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200
